added steps for Go Gin SDK
short-loop/installation-guide pull request #2
Opened 2023-01-24 06:18 UTC by aayush-chodvadiya

2023-01-24 06:21 UTC, deepakthakur143 requested changes

2023-01-24 06:21 UTC, deepakthakur143 commented on sdk.md
> +$ go get github.com/short-loop/shortloop-go@latest
can we put the exact version here

2023-01-25 09:55 UTC, sumit-shortloop commented on sdk.md
> +    ApplicationName:   "service-name",
Can we add comments here indicating that these are variables that user has to replace? (Refer the Java one.)

2023-01-25 09:57 UTC, sumit-shortloop commented on sdk.md
> +    ApplicationName:   "service-name",
In Java projects; people don't hard code these things as they are Environment specific as well. 
So they are extracted out in properties file.
Assuming the same would be true for Go as well. 
And our SDK should read these properties from external config. So these two lines shouldn't be needed here. 

How do other projects (like Sentry) asks for the initialisation?

2023-01-25 09:59 UTC, sumit-shortloop commented on sdk.md
> +router := gin.Default()
`router := gin.Default()` 
this is not part of our SDK; right? 
So should be mentioned outside. 

Is there other ways how Router are initialised?

2023-01-25 10:02 UTC, sumit-shortloop commented on sdk.md
> +$ go get github.com/short-loop/shortloop-go@v0.0.1
this should not be required, right? 
as developers in their project are not installing individual dependency one by one. 
(Assuming this will be picked by default in their build process. Like in `mvn clean install` or `npm install` 
Let me know if this is not how it works in go.)

2023-01-25 10:02 UTC, sumit-shortloop requested changes
Requesting changes.

2023-01-26 05:16 UTC, aayush-chodvadiya commented on sdk.md
> +$ go get github.com/short-loop/shortloop-go@v0.0.1
actually when you run go get command it downloads the version specified and updates the go.mod file.  It adds the specified dependency as well as indirect dependencies (only updates if already there) in go.mod file. indirect dependencies are dependencies used by specified dependency. 

this same process of updating indirect dependencies is not done when you just add it manually and try to build it. for updating that again it suggests some command like go mod download dependency or go get. as at the end you end up doing go get or go mod download.
go get is older than go mod download and so almost every package gives this in their documentation.

I referred sentry and aws sdk docs 
- https://docs.sentry.io/platforms/go/
- https://github.com/aws/aws-sdk-go

2023-01-26 05:19 UTC, aayush-chodvadiya commented on sdk.md
> +router := gin.Default()
I gave an example how it would look like because without it poeple won't know from where router variable came. gin.Default() gives gin engine with default logger and recovery middlewares. other way is gin.New() which gives engine with no middlewares and then add middlewares to it.

2023-01-26 05:20 UTC, aayush-chodvadiya commented on sdk.md
> +    ApplicationName:   "service-name",
there is no official properties file in go or gin. people can read values from env variables. However there are 3rd party packages which help to read and update properties file. it can be project specific.

So Sentry assumes you will give these values either through code as options from your custom config or set these values in ENV. 
1. If you pass it in code as options then it won't read from env.
2. If not passed from code it will read from ENV.

Right now in our SDK I implemented only 1st point. (not reading from env)
If you want I can make same behavior as sentry.

2023-01-26 07:59 UTC, sumit-shortloop approved these changes

2023-01-26 09:25 UTC, merged